### PR TITLE
todo application with react frontend and ruby on rails backend having…

### PR DESCRIPTION
**Pull request by rachana-uniyal**
Task 1: CRUD operations for task management

1. Implemented CRUD operations with react frontend and rails backend.
2. User can add, delete, update and read his todo list.
3. On delete strikeout and checkbox functionalities.

Note
1. Please set username in database.yml file before running application.

### CODE REVIEW

**Comment by rkr090** [comment]
@rachana-uniyal Please raise the PR in the following repository.
https://github.com/saeloun/rachana-assessment

**Comment by rachana-uniyal** [comment]
> @rachana-uniyal Please raise the PR in the following repository.
> https://github.com/saeloun/rachana-assessment
@rkr090 
I am facing issues while creating pull request. Please help me with that.

**Comment by rkr090** [comment]
@rachana-uniyal It could be because you have the wrong origin after you clone `plate`. You can update the origin to be `git@github.com:saeloun/rachana-assessment.git`

https://docs.github.com/en/github/using-git/changing-a-remotes-url

**Comment by rachana-uniyal** [comment]
> @rachana-uniyal It could be because you have the wrong origin after you clone `plate`. You can update the origin to be `git@github.com:saeloun/rachana-assessment.git`
> 
> https://docs.github.com/en/github/using-git/changing-a-remotes-url

@rkr090 
After setting origin as git@github.com:saeloun/rachana-assessment.git , I executed command 'git push origin master' and it is giving the following error

Warning: Permanently added 'github.com,13.234.210.38' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by rkr090** [comment]
@rachana-uniyal I do not know what the issue could be. Please look here:
https://docs.github.com/en/github/authenticating-to-github/error-permission-denied-publickey

I see that you have already pushed to `master` so it must be working?

**Comment by rachana-uniyal** [comment]
> @rachana-uniyal I do not know what the issue could be. Please look here:
> https://docs.github.com/en/github/authenticating-to-github/error-permission-denied-publickey
> 
> I see that you have already pushed to `master` so it must be working?

@rkr090 
Yes, I have pushed but I am not able to make a pull request. What should I do ?

**Comment by rkr090** [comment]
You cannot make a pull request because you have pushed to the base branch i.e master. Please just mention on the issue that you have pushed to the `master` branch and create a PR for followup issues.

**Comment by rachana-uniyal** [comment]
> You cannot make a pull request because you have pushed to the base branch i.e master. Please just mention on the issue that you have pushed to the `master` branch and create a PR for followup issues.

@rkr090 
Thankyou.

**Pull request closed without merging**
